testing_webpage/api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^get_public_posts$', views.get_public_posts, name='get_public_posts'),
    url(r'^add_messages$', views.add_messages, name='add_messages'),
    url(r'^save_leads$', views.save_leads, name='save_leads'),

    # API v1
    url(r'^v1/register$', views.register, name='register'),
    url(r'^v1/get_work_areas', views.get_work_areas, name='get_work_areas'),
    url(r'^v1/get_cities$', views.get_cities, name='get_cities'),
    url(r'^v1/get_campaigns$', views.get_campaigns, name='get_campaigns'),

]

testing_webpage/business/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from business import views

app_name = 'business'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # LOGIN AND LOGOUT
    url(r'^login$', auth_views.login, {'template_name': 'business/login.html', 'extra_context': {'error_message': ''}}, name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': 'business:index'}, name='logout'),
    # CREATE CAMPAIGN
    url(r'^seleccion_gratis$', views.start, name='start'),
    url(r'^seleccion_gratis_enviar$', views.start_post, name='start_post'),
    # CREATE CAMPAIGN WHEN USER IS LOGGED
    url(r'^crear_enviar$', views.create_post, name='create_post'),
    # BUSINESS USER LOGGED
    url(r'^campañas/(?P<business_user_id>\d+)$', views.business_campaigns, name='business_campaigns'),
    url(r'^resumen/(?P<campaign_id>\d+)$', views.summary, name='summary'),
    url(r'^online_demo$', views.online_demo, name='online_demo'),
    url(r'^tablero_de_control/(?P<business_user_id>\d+)/(?P<campaign_id>\d+)/(?P<state_name>.*)/$', views.dashboard, name='dashboard'),
    url(r'^perfil_del_candidato/(?P<pk>\d+)$', views.candidate_profile, name='candidate_profile'),
    # CONTACT
    url(r'^contactanos$', views.contact_form, name='contact_form'),
    url(r'^contact_form_post$', views.contact_form_post, name='contact_form_post'),
    # START
    url(r'^get_work_area_requirement/(?P<work_area_id>\d+)$', views.get_work_area_requirement, name='get_work_area_requirement'),
    # PAYU
    url(r'payment_confirmation$', views.payment_confirmation, name='payment_confirmation'),


    url(r'^save_comments$', views.save_comments, name='save_comments'),
    # TODO: This search url should be deleted?
    url(r'^search$', views.search, name='search'),
    url(r'^results$', views.calculate_result, name='results'),
    url(r'^business_signup$', views.business_signup, name='business_signup'),
    url(r'^home$', views.home, name='home'),
    # TODO: Worst hack ever, replace for something like: \?id=[0-9]+
    url(r'^results/(?P<pk>\d+)$', views.render_result, name='render_result'),
    url(r'^plan/(?P<pk>\d+)$', views.plan, name='plan'),
]

'''
url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    auth_views.password_reset_confirm, name='password_reset_confirm'),
url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
'''

testing_webpage/dashboard/urls.py
from django.conf.urls import url

from . import views
from . import stats

app_name = 'dashboard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # All tests
    url(r'^tests_list$', views.tests_list, name='tests_list'),

    # Campaign
    url(r'^campaign/(?P<campaign_id>\d+)$', views.edit_campaign_candidates, name='campaign'),
    url(r'^campaign/new$', views.new_campaign, name='new_campaign'),
    url(r'^campaign/create$', views.create_campaign, name='create_campaign'),
    url(r'^campaign/edit/(?P<pk>\d+)$', views.edit_campaign, name='edit_campaign'),
    url(r'^campaign/update_basic_properties$', views.update_basic_properties),
    url(r'^campaign/delete/(?P<pk>\d+)$', views.delete_campaign, name='delete_campaign'),
    url(r'^campaign/candidate/(?P<candidate_id>\d+)$', views.candidate_detail, name='candidate_detail'),

    # Campaign tests
    url(r'^campaign/(?P<pk>\d+)/add_test$', views.add_test),
    url(r'^campaign/(?P<pk>\d+)/delete_test$', views.delete_test),
    url(r'^campaign/(?P<pk>\d+)/tests$', views.tests),

    # Test
    # url(r'^', include('home.urls', namespace='home')),
    url(r'^test/(?P<pk>\d+)$', views.edit_test, name='test_edit'),
    url(r'^test/new$', views.new_test, name='new_test'),
    url(r'^test/save$', views.save_test, name='save_test'),
    url(r'^test/update/(?P<pk>\d+)$', views.update_test, name='update_test'),
    url(r'^test/delete_question$', views.delete_question, name='delete_question'),
    url(r'^test/delete_answer$', views.delete_answer, name='delete_answer'),
    url(r'^test/duplicate/(?P<pk>\d+)$', views.duplicate_test, name='duplicate_test'),

    # Bullets
    url(r'^campaign/(?P<pk>\d+)/bullets$', views.bullets),
    url(r'^campaign/update_bullets$', views.update_bullets),
    url(r'^campaign/delete_bullet$', views.delete_bullet),

    # Interview
    url(r'^edit_intro_video$', views.edit_intro_video, name='edit_intro_video'),
    url(r'^campaign/interview/(?P<pk>\d+)$', views.interview, name='interview'),
    url(r'^campaign/check_interview$', views.check_interview, name='check_interview'),
    url(r'^campaign/interview/create_interview_question$', views.create_interview_question, name='create_interview_question'),
    url(r'^campaign/interview/update_interview_question$', views.update_interview_question, name='update_interview_question'),
    url(r'^campaign/interview/delete_interview_question$', views.delete_interview_question, name='delete_interview_question'),

    # Auto messenger
    url(r'^send_new_contacts$', views.send_new_contacts, name='send_new_contacts'),
    url(r'^send_messages$', views.send_messages, name='send_messages'),

    # stats
    url(r'^candidates_stats$', stats.candidates_count, name='candidates_stats'),
    url(r'^campaign_stats$', stats.campaign_count, name='campaign_stats'),
    url(r'^number_of_forecasts$', stats.number_of_forecasts, name='number_of_forecasts'),
    url(r'^positive_forecasts$', stats.positive_forecasts, name='positive_forecasts'),
    url(r'^negative_forecasts$', stats.negative_forecasts, name='negative_forecasts'),

]

testing_webpage/dashboard/views.py
import json
import common
from django.core import serializers
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.db.models import Q
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from beta_invite.models import Campaign, Test, TestType, BulletType, Interview, Survey, Bullet, QuestionType, Question, Answer, CampaignState
from business.models import Company
from dashboard.models import Candidate, Message, Screening
from dashboard import constants as cts
from beta_invite.util import email_sender
from beta_invite.views import get_drop_down_values
from dashboard import interview_module, candidate_module, campaign_module, test_module
from match import model
from api.models import LeadMessage
from business.models import BusinessUser

CANDIDATE_FORECAST_LIMIT = 20

'''
                     DON'T DELETE, THIS WILL BE USEFUL FOR AUTOMATIC STATE CHANGES OR SORTING
def sort_users_by_campaign_count(business_users):
    business_users = [(b, b.campaigns.filter(removed=False).count()) for b in business_users]
    business_users.sort(key=lambda x: x[1], reverse=True)
    return [b for b, count in business_users if count > 0]


def get_business_users_order_by_active_campaigns():
    weeks_old = 5
    weeks_ago = datetime.datetime.today() - datetime.timedelta(weeks=weeks_old)
    new_business_users = BusinessUser.objects.filter(created_at__gte=weeks_ago).all()
    old_business_users = BusinessUser.objects.filter(created_at__lt=weeks_ago).all()

    return sort_users_by_campaign_count(new_business_users) + sort_users_by_campaign_count(old_business_users)
'''


@login_required
def index(request):
    """
    Args:
        request: HTTP
    Returns: renders main view with a list of campaigns
    """

    # TODO: this basic login... works but the real admin users can be used instead
    # TODO: how to add the same auth to all the app????
    if common.not_admin_user(request):
        return redirect('business:login')
    campaigns = Campaign.objects.filter(removed=False).order_by('-created_at', 'state', 'title_es').all()

    for campaign in campaigns:
        common.calculate_operational_efficiency(campaign)

    return render(request, cts.MAIN_DASHBOARD, {'campaigns': campaigns})

# ------------------------------- CAMPAIGN -------------------------------


def tests_list(request):
    """
    :param request: HTTP request
    :return: render view
    """

    tests = Test.get_all()

    return render(request, cts.TEST_LIST, {'tests': tests})


def candidate_detail(request, candidate_id):
    """
    :param request: HTTP request
    :param candidate_id: int Candidate id
    :return: render view
    """
    return render(request, cts.CANDIDATE_DETAIL, {'candidate': Candidate.objects.get(pk=candidate_id)})


def add_to_message_queue(candidates, text):
    """
    Adds objects to the message table. So later on this table will serve as a message queue.
    :param candidates: list of candidates.
    :param text: string
    :return: writes on table messages to be sent.
    """
    for candidate in candidates:
        Message(candidate=candidate, text=text).save()


def update_candidate_forecast(campaign):
    """
    Updates up to CANDIDATE_FORECAST_LIMIT per execution, due to time limit on production server, and possible crash.
    :return: updates.
    """
    candidates = Candidate.objects.filter(Q(match_classification=None) & Q(campaign=campaign)).all()
    candidates = candidates[:min(len(candidates), CANDIDATE_FORECAST_LIMIT)]
    model.predict_match_and_save(candidates)


# TODO: use Ajax to optimize rendering. Has no graphics therefore is very low priority.
def edit_campaign_candidates(request, campaign_id):
    """
    Args:
        request: HTTP
        campaign_id: campaign primary key
    Returns: This controls the candidates dashboard
    """
    campaign = Campaign.objects.get(pk=campaign_id)

    action = request.POST.get('action')
    candidate_id = request.POST.get('candidate_id')
    if candidate_id is not None:
        candidate = Candidate.objects.get(pk=int(candidate_id))

        if action == 'update':
            candidate_module.update_candidate_manually(request, candidate)
        elif action == 'add':
            candidate_module.add_candidate_to_campaign(request, candidate)
        elif action == 'remove':
            candidate_module.remove_candidate(candidate)
        elif action == 'move':
            if candidate_module.add_candidate_to_campaign(request, candidate):  # only erase if has add successfully
                candidate_module.remove_candidate(candidate)

    # TODO: can be done with JS in smarter way???
    # enters here when sending an email
    if request.POST.get('send_mail') is not None:

        candidates = candidate_module.get_checked_box_candidates(campaign_id, request)

        email_sender.send(objects=candidates,
                          language_code=request.LANGUAGE_CODE,
                          body_input=request.POST.get('email_body'),
                          subject=candidate_module.get_subject(request, campaign_id),
                          with_localization=False,
                          body_is_filename=False)

    if request.POST.get('send_message') is not None:
        candidates = candidate_module.get_checked_box_candidates(campaign_id, request)
        add_to_message_queue(candidates, request.POST.get('email_body'))

    update_candidate_forecast(campaign)

    params, states = candidate_module.get_rendering_data(campaign_id)

    # all campaigns except the current one.
    campaigns_to_move_to = Campaign.objects.exclude(pk=campaign_id)

    params['states'] = states
    params['campaign_id'] = campaign_id
    params['screenings'] = [s for s in Screening.objects.all()]
    params['campaigns'] = campaigns_to_move_to
    params['current_campaign'] = Campaign.objects.get(pk=campaign_id)

    return render(request, cts.EDIT_CANDIDATES, params)


def new_campaign(request):

    countries, cities, education, professions, work_areas, genders = get_drop_down_values(request.LANGUAGE_CODE)
    bullet_types_json = serializers.serialize("json", BulletType.objects.all())

    return render(request, cts.NEW_OR_EDIT_CAMPAIGN, {'countries': countries,
                                                      'education': education,
                                                      'professions': professions,
                                                      'bullet_types_json': bullet_types_json,
                                                      'action_url': '/dashboard/campaign/create',
                                                      'title': 'Nueva Campaña',
                                                      })


def create_campaign(request):
    """
    When you are in a new campaign and you save the model
    Args:
        request: HTTP
    Returns:
    """

    campaign_module.create_campaign(request)

    # in this specific case gotta go back. Because if the user stays modifying the campaign on the 'new' template it
    # will create additional campaigns instead of modifying the first creation.
    return redirect('/dashboard')


def edit_campaign(request, pk):
    """
    Args:
        request: HTTP
        pk: campaign_id
    Returns: Renders basic properties of a campaign
    """
    campaign = Campaign.objects.get(pk=pk)
    countries, cities, education, professions, work_areas, genders = get_drop_down_values(request.LANGUAGE_CODE)
    business_user = common.get_business_user_with_campaign(campaign, 'object')
    if not business_user:
        company = ""
    else:
        company = business_user.company

    return render(request, cts.NEW_OR_EDIT_CAMPAIGN, {'countries': countries,
                                                      'cities': cities,
                                                      'education': education,
                                                      'professions': professions,
                                                      'work_areas': work_areas,
                                                      'campaign': campaign,
                                                      'action_url': '/dashboard/campaign/update_basic_properties',
                                                      'title': 'Update {}'.format(campaign.title_es),
                                                      'campaign_states': CampaignState.objects.all(),
                                                      'company': company
                                                      })


def update_basic_properties(request):
    """
    Args:
        request: HTTP.
    Returns: Updates just the basics of a campaign.
    """
    campaign = common.get_campaign_from_request(request)

    campaign_module.update_campaign_basic_properties(campaign, request)
    business_user = common.get_business_user_with_campaign(campaign, 'object')
    if business_user:
        company = business_user.company
        if company:
            company.name = request.POST.get('company')
            company.save()
        else:
            company = Company()
            company.name = request.POST.get('company')
            company.save()
            business_user.company = company
            business_user.save()
    else:
        pass

    return campaign_module.get_campaign_edit_url(campaign)


def delete_campaign(request, pk):

    campaign = Campaign.objects.get(pk=pk)

    if campaign:
        campaign.removed = True
        campaign.save()

    return redirect('/dashboard')


# ------------------------------- CAMPAIGN TESTS -------------------------------


def tests(request, pk):
    """
    Args:
        request: HTTP
        pk: campaign_id
    Returns: Renders the list of tests for a given campaign
    """
    campaign = Campaign.objects.get(pk=pk)

    return render(request, cts.TESTS, {'campaign': campaign,

testing_webpage/dashboard/templates/dashboard/edit_intro_video.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}

    <meta charset="UTF-8">
    <title>Edit interview intro video</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Ziggeo stuff-->
    <link rel="stylesheet" href="//assets-cdn.ziggeo.com/v1-stable/ziggeo.css" />
    <script src="//assets-cdn.ziggeo.com/v1-stable/ziggeo.js"></script>
    <script>ZiggeoApi.token = "{{ziggeo_api_key}}";</script>

    <script type="text/javascript" src="{% static 'dashboard/js/edit_intro_video.js' %}"></script>

</head>
<body>

    <form action="./" method="post"
           enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" value="HOME">
    </form>

    <h2>Current intro video</h2>

    {% if current_video %}

        <ziggeoplayer ziggeo-video='{{current_video}}'
            ziggeo-width=320
            ziggeo-height=240>
        </ziggeoplayer>

    {% endif %}

    <h2>Record a new intro video</h2>

    <ziggeorecorder ziggeo-timelimit=60
        ziggeo-width=320
        ziggeo-height=240
        ziggeo-theme='modern'
        id="myRecorder">
    </ziggeorecorder>

    <br>

    <form action="#" method="post" id="main_form_id">
        {% csrf_token %}
        <input type="button" class="btn btn-success" name="save_changes" value="Save!"
            onclick="submit_form()">
    </form>

</body>
</html>

testing_webpage/dashboard/templates/dashboard/index.html
{% extends 'base.html'%}
{% load static %}
{% load i18n %}
{% load app_filters %}
{% load compress %}
{% block title %}DASHBOARD{% endblock %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/css/index.css' %}">
{% endblock %}
{% block content %}
<div class="row">
    <form action="{% url 'business:results' %}">
        <input style="width:500px;" id="search-input" type="text" name="search_text" placeholder="{% trans 'Search positions (eg android developer)' %}">
    </form>
</div>
<div class="row">
    <h2>Stats for nerds</h2>
    <p><a href="{% url 'dashboard:candidates_stats' %}" target="_blank">Total candidates per month</a></p>
    <p><a href="{% url 'dashboard:campaign_stats' %}" target="_blank">Total campaigns per month</a></p>
    <p><a href="{% url 'dashboard:number_of_forecasts' %}" target="_blank">Total Forecasts</a></p>
    <p><a href="{% url 'dashboard:positive_forecasts' %}" target="_blank">Positive Forecasts</a></p>
    <p><a href="{% url 'dashboard:negative_forecasts' %}" target="_blank">Negative Forecasts</a></p>

    <p class="tests"><a href="{% url 'dashboard:tests_list' %}" target="_blank">Ver Pruebas</a></p>
    <h2 style="text-align:center; font-size:60px;">CAMPAÑAS</h2>
    <p><a href="campaign/new">Nueva campaña</a></p>
</div>
<div class="row">
    <div class="col-lg-6">
        <ul>
            <h2 class="center">PAGAS</h2>
            {% for campaign in campaigns %}
            {% if not campaign.free_trial %}
            <div class="campaign-div">
                <div class="row">
                    <p class="tittle">{{ campaign.title_es }}</p>
                <div class="col-lg-5">

                    <a href="{{ campaign|get_campaign_url }}" target="_blank">Ver publicación (long_form)</a>
                    <br>
                    <a href="{% url 'dashboard:campaign' campaign.id %}" target="_blank">Ver candidatos</a>
                    <br>
                    <a href="{% url 'dashboard:edit_campaign' campaign.id %}" target="_blank">Editar campaña</a>
                    <br>
                    <a href="{% url 'dashboard:campaign' campaign.id %}/bullets" target="_blank">Bullets</a>
                    <br>
                    <a href="{% url 'business:summary' campaign_id=campaign.id %}" target="_blank">Ver Dashboard Empresarial</a>
                    <br>
                    <a href="{% url 'dashboard:campaign' campaign.id %}/tests" target="_blank">Ver pruebas</a>
                    <br>
                    <br>
                    <form action="{% url 'dashboard:delete_campaign'  campaign.id %}" method="post">
                        {% csrf_token %}
                        <input type="button" class="btn btn-danger" value="Delete!" onclick="this.form.submit();">
                    </form>
                </div>
                <div class="col-lg-7">
                    <p><b>EMPRESA:</b> {{ campaign|get_business_user_company_with_campaign }}</p>
                    <p><b>REPRESENTANTE:</b> {{ campaign|get_business_user_name_with_campaign }}</p>
                    <p><b>ESTADO:</b> {{ campaign.state.name_es }}</p>
                    <p><b>FECHA DE CREACIÓN:</b> {{ campaign.local_date }}</p>
                    {% if campaign.operational_efficiency %}
                    <p><b>EFICIENCIA (STC/(STC + RECHAZADOS MANUALES)):</b> {% widthratio campaign.operational_efficiency 1 100 %}%</p>
                    {% endif %}
                </div>
                </div>
            </div>
            <br>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
    <div class="col-lg-6">
        <ul>
            <h2 class="center">GRATIS</h2>
            {% for campaign in campaigns %}
            {% if campaign.free_trial %}
                <div class="campaign-div">
                <div class="row">
                    <p class="tittle">{{ campaign.title_es }}</p>
                <div class="col-lg-5">
                    <a href="{{ campaign|get_campaign_url }}" target="_blank">Ver publicación (long_form)</a>
                    <br>
                    <a href="{% url 'dashboard:campaign' campaign.id %}" target="_blank">Ver candidatos</a>
                    <br>
                    <a href="{% url 'dashboard:edit_campaign' campaign.id %}" target="_blank">Editar campaña</a>
                    <br>
                    <a href="{% url 'dashboard:campaign' campaign.id %}/bullets" target="_blank">Bullets</a>
                    <br>
                    <a href="{% url 'business:summary' campaign_id=campaign.id %}" target="_blank">Ver Dashboard Empresarial</a>
                    <br>
                    <a href="{% url 'dashboard:campaign' campaign.id %}/tests" target="_blank">Ver pruebas</a>
                    <br>
                    <br>
                    <form action="{% url 'dashboard:delete_campaign'  campaign.id %}" method="post">
                        {% csrf_token %}
                        <input type="button" class="btn btn-danger" value="Delete!" onclick="this.form.submit();">
                    </form>
                </div>
                <div class="col-lg-7">
                    <p><b>EMPRESA:</b> {{ campaign|get_business_user_company_with_campaign }}</p>
                    <p><b>REPRESENTANTE:</b> {{ campaign|get_business_user_name_with_campaign }}</p>
                    <p><b>ESTADO:</b> {{ campaign.state.name_es }}</p>
                    <p><b>FECHA DE CREACIÓN:</b> {{ campaign.local_date }}</p>
                    {% if campaign.operational_efficiency %}
                    <p><b>EFICIENCIA (STC/(STC + RECHAZADOS MANUALES)):</b> {% widthratio campaign.operational_efficiency 1 100 %}%</p>
                    {% endif %}
                </div>
                </div>
            </div>
            <br>
            {% endif %}
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

testing_webpage/dashboard/templates/dashboard/stats_index.html
<!DOCTYPE html>
<html>
<head>
	<title>stats</title>
	{% load static %}
   <script type="text/javascript" src="{% static 'fusioncharts/js/fusioncharts.js' %}"></script>
   <script type="text/javascript" src="{% static 'fusioncharts/js/themes/fusioncharts.theme.fint.js' %}"></script>
</head>
<body>
	<div id="chart-1">{{ output|safe }}</div>
</body>
</html>