testing_webpage/api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^get_public_posts$', views.get_public_posts, name='get_public_posts'),
    url(r'^add_messages$', views.add_messages, name='add_messages'),
    url(r'^save_leads$', views.save_leads, name='save_leads'),

    # API v1
    url(r'^v1/register$', views.register, name='register'),
    url(r'^v1/get_work_areas', views.get_work_areas, name='get_work_areas'),
    url(r'^v1/get_cities$', views.get_cities, name='get_cities'),
    url(r'^v1/get_campaigns$', views.get_campaigns, name='get_campaigns'),

]

testing_webpage/beta_invite/urls.py
from django.conf.urls import url

from . import views

app_name = 'beta_invite'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^registro$', views.register, name='register'),
    url(r'^pruebas$', views.tests, name='tests'),
    url(r'^test_result$', views.get_test_result, name='test_result'),
    url(r'^add_cv$', views.add_cv, name='add_cv'),
    url(r'^add_cv_changes$', views.add_cv_changes),
    url(r'^additional_info$', views.additional_info, name='additional_info'),
    url(r'^save_partial_additional_info$', views.save_partial_additional_info, name='save_partial_additional_info'),
    url(r'^active_campaigns', views.active_campaigns, name='active_campaigns'),
    url(r'^security_politics', views.security_politics, name='security_politics'),
]

testing_webpage/testing_webpage/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^trabajos$', views.jobs, name='index'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^servicio_de_empleo/', include('beta_invite.urls')),
    url(r'^seleccion_de_personal/', include('business.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^admin/', admin.site.urls)
]

urlpatterns += i18n_patterns(
    url(r'^staffing$', views.index, name='index'),
    url(r'^sitemap.xml$', views.sitemap, name='sitemap'),
    url(r'^BingSiteAuth.xml$', views.bing_site_auth, name='BingSiteAuth'),
    url(r'^robots.txt$', views.robots, name='robots')
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testing_webpage/testing_webpage/models.py
from django.db import models
from picklefield.fields import PickledObjectField


from beta_invite.models import EmailType
from business.models import BusinessUser
from dashboard.models import Candidate


class CandidateEmailSent(models.Model):

    email_type = models.ForeignKey(EmailType, on_delete=models.DO_NOTHING)
    candidate = models.ForeignKey(Candidate, on_delete=models.DO_NOTHING, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'id={0}, candidate_id={1}, email_type={2}'.format(self.pk, self.candidate.id, self.email_type)

    # adds custom table name
    class Meta:
        db_table = 'candidate_emails_sent'


class BusinessUserEmailSent(models.Model):

    email_type = models.ForeignKey(EmailType, on_delete=models.DO_NOTHING)
    business_user = models.ForeignKey(BusinessUser, on_delete=models.DO_NOTHING, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'id={0}, candidate_id={1}, email_type={2}'.format(self.pk, self.business_user.id, self.email_type)

    # adds custom table name
    class Meta:
        db_table = 'business_user_emails_sent'


class CandidatePendingEmail(models.Model):

    candidates = models.ManyToManyField(Candidate)
    language_code = models.CharField(max_length=3)
    body_input = models.CharField(max_length=10000)
    subject = models.CharField(max_length=200)
    email_type = models.ForeignKey(EmailType, on_delete=models.DO_NOTHING)

    # optional
    with_localization = models.BooleanField(default=True)
    body_is_filename = models.BooleanField(default=True)
    override_dict = PickledObjectField(default={})

    # internal
    sent = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'id={0}'.format(self.pk)

    @staticmethod
    def add_to_queue(**kwargs):

        candidates = kwargs.pop('candidates', None)

        email = CandidatePendingEmail(**kwargs)
        email.save()
        email.save_candidates(candidates)

    def save_candidates(self, candidates):
        """
        Can __init__ with 1 candidate or a list  of candidates.
        :param candidates:
        :return:
        """
        if candidates and type(candidates) != list:
            candidates = [candidates]

        self.candidates = candidates
        self.save()

    # adds custom table name
    class Meta:
        db_table = 'candidate_pending_emails'


class BusinessUserPendingEmail(models.Model):

    business_users = models.ManyToManyField(BusinessUser)
    language_code = models.CharField(max_length=3)
    body_input = models.CharField(max_length=10000)
    subject = models.CharField(max_length=200)
    email_type = models.ForeignKey(EmailType, on_delete=models.DO_NOTHING, null=True)

    # optional
    with_localization = models.BooleanField(default=True)
    body_is_filename = models.BooleanField(default=True)
    override_dict = PickledObjectField(default={})

    # internal
    sent = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'id={0}'.format(self.pk)

    @staticmethod
    def add_to_queue(**kwargs):

        business_users = kwargs.pop('business_users', None)

        email = BusinessUserPendingEmail(**kwargs)
        email.save()
        email.save_business_users(business_users)

    def save_business_users(self, business_users):
        """
        Can __init__ with 1 business_user or a list of business_users.
        :param business_users:
        :return:
        """
        if business_users and type(business_users) != list:
            business_users = [business_users]

        self.business_users = business_users
        self.save()

    # adds custom table name
    class Meta:
        db_table = 'business_user_pending_emails'

testing_webpage/testing_webpage/views.py
from django.shortcuts import render
from testing_webpage import constants as cts
from beta_invite.models import Campaign
from django.db.models import Q


def index(request):
    """
    will render the intro
    """
    return render(request, cts.INDEX_VIEW_PATH)


def sitemap(request):
    return render(request, 'testing_webpage/sitemap.xml', {}, content_type="application/xhtml+xml")


def bing_site_auth(request):
    return render(request, 'testing_webpage/BingSiteAuth.xml', {}, content_type="application/xhtml+xml")


def robots(request):
    return render(request, 'testing_webpage/robots.txt', {}, content_type="application/xhtml+txt")


def jobs(request):
    segment_code = request.GET.get('segment_code')
    if segment_code is None:  # if code not found will return everything
        return render(request, cts.JOBS_VIEW_PATH,
                      {'active_campaigns': Campaign.objects.filter(~Q(title_es=None),
                                                                   state__code__in=['I', 'A'],
                                                                   removed=False)})
    else:
        return render(request, cts.JOBS_VIEW_PATH,
                      {'active_campaigns': Campaign.objects.filter(~Q(title_es=None),
                                                                   state__code__in=['I', 'A'], removed=False,
                                                                   work_area__segment__code=segment_code
                                                                   )})

testing_webpage/testing_webpage/templates/testing_webpage/index.html
{% extends 'no_header_base.html'%}
{% load static %}
{% load i18n %}
{% load app_filters %}
{% load compress %}
{% block title %}{% trans 'Empleos en Colombia | Ofertas de Trabajo. Buscar empleo' %}{% endblock %}
{% block extra_meta %}
    <meta name="description"  content="Encuentra vacantes, trabajos y ofertas de empleo en Colombia, Chile, Ecuador, Perú y Argentina. Registra gratis tu hoja de vida en nuestra bolsa de empleo." />
    <meta name="keywords" content="computrabajo, servicio de empleo, empleo, ofertas de empleo, empleos, trabajos, trabaja con nosotros, buscador de empleo, bolsa de empleo, agencia de empleo" />
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'testing_webpage/css/index.css' %}">
{% endblock %}
{% block extra_js %}
    <script type="text/javascript" src="{% static 'business/js/index.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="fix-content-space">
        <div class="row blankbanner"></div>
        <div class="section1">
            <div class="row" id="main-copy">
                <h1 id="main-copy-title">{% trans 'Your ideal job' %}</h1>
                <p id="main-copy-big-title">{% trans 'AWAITS YOU'%}</p>
                <span class="first-description">{% trans 'Leave us your mail, we do the rest' %}</span>
                <form action="{% url 'beta_invite:index' %}">
                    <button class="button-cta" role="button">{% trans 'Apply' %}</button>
                </form>
            </div>
            <div class="row blankabout responsive-no"></div>
            <div class="blankabout no-space"></div>
        </div>
        <div class="row section2">
            <div class="col-lg-6 col-md-6 col-xs-12 woman-working"></div>
            <div class="col-lg-6 col-md-6 col-xs-12 description2">
                <h5>{% trans 'At PeakU we help you find the job you are looking for in companies that fit your profile, experience and salary.' %}</h5>
                <h4>{% trans 'You can apply to all our job offers easily and without any cost' %}</h4>
            </div>
        </div>
        <div class="row conectors-row">
            <div class="col-lg-12 col-md-12 col-xs-12 conectors">
                <div class="play-div">
                    <a href="https://www.youtube.com/watch?v=QbNDO2ShXIs" target="_blank">
                        <img class="play-button" src="{% static 'testing_webpage/img/play_button.png' %}">
                        <span class="video">{% trans 'WATCH VIDEO' %}</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="row section3">
            <div class="col-lg-push-6 col-md-6 col-xs-12 workg-people"></div>
            <div class="col-lg-pull-6 col-md-6 col-xs-12 description3">
                <h3>{% trans 'Work with the most important companies' %}</h3>
                <h2>{% trans 'in the world' %}</h2>
                <br>
                <h5 class="last-description">{% trans 'With PeakU you apply only once and you have access to many job openings with multiple companies and multiple roles' %}</h5>
            </div>
        </div>
    </div>
{% endblock %}

testing_webpage/testing_webpage/templates/testing_webpage/jobs.html
{% extends 'transparent_header_base.html'%}
{% load static %}
{% load i18n %}
{% load app_filters %}
{% load compress %}
{% block title %}{% trans 'Jobs' %}{% endblock %}
{% block extra_meta %}
<meta name="description"  content="En PeakU te ayudamos a encontrar el empleo que buscas en compañias que se ajustan a tu perfil, experiencia y salario. Somos una empresa que trabaja en selección de personal, no una temporal." />
<meta name="keywords" content="computrabajo, servicio de empleo, empleo, empleos, trabajos, trabaja con nosotros, buscador de empleo, bolsa de empleo, agencia de empleo" />
{% endblock %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'beta_invite/css/index.css' %}">
{% endblock %}
{% block extra_js %}
<script type="text/javascript" src="{% static 'beta_invite/js/index.js' %}"></script>
{% endblock %}
{% block content %}
<div class="row" style="margin-bottom:40px;">
    <h2 class="descriptions">{% trans "AVAILABLE POSITIONS" %}</h2>
</div>
<div class="jobs-background">
    <!----------------------------------------------SECTION 1---------------------------------------------------------->
    <div id="overlay-signup">
        <div class="form-image">
            <form class="only-register-form" action="{% url 'beta_invite:register' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset>
                    <span class="exitDingbat" onclick="off_signup()">X</span>
                    <br>
                    <br>
                    <input type="hidden" name="campaign_id" value="{{ campaign_id }}"/>
                    <input type="hidden" name="candidate_id" value="{{ candidate.pk }}"/>
                    <span>{% trans 'Your Full Name' %}</span>
                    <input class="form-input" id="name" type="text" name="name" required="required" pattern="[A-Za-z\sáéíóúÑñÜüÁÉÍÓÚ]{1,200}">
                    {% if campaign.has_email %}
                    <span>{% trans 'Your email' %}</span>
                    <input class="form-input" id="email" type="email" name="email" required="required">
                    {% endif %}
                    <span>{% trans 'Your phone' %}</span>
                    <input class="form-input" id="phone" type="tel" name="phone" required="required" pattern="[0-9\(\)\+\-\s\.extension]{7,40}">
                    <span>Ciudad de residencia</span>
                    <select class="form-input white" name="city_id" >
                        <option value="{{ default_city.id }}">{{ default_city.name }}</option>
                        {% for city in cities %}
                        <option value="{{ city.id }}">{{ city.name }}</option>
                        {% endfor %}
                    </select>
                    <span>Área de trabajo</span>
                    <select class="form-input white" name="work_area_id" required>
                        <option value="" selected disabled></option>
                        {% for work_area in work_areas %}
                        <option value="{{ work_area.id }}">{{ work_area.name }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <div>
                        <input type="file" id="file" name="curriculum_url" class="form-inputfile" onchange="pressed()">
                        <label for="file" id="fileLabel">{% trans "Upload your resume" %}</label>
                        <label class="form-checkbox-container">
                        <input class="form-checkbox" type="checkbox" id="politics" name="politics" required>
                        <a href="security_politics" target="_blank"> He leído y acepto las políticas de privacidad</a>
                        </label>
                    </div>
                    <input class="submit" type="submit" id="submit" value="{% trans 'Sure!' %}">
                </fieldset>
                </span>
            </form>
        </div>
    </div>
    <br>
    <br>
    <div>
        {% for campaign in active_campaigns %}
        <div class="campaign-div">
            <a href="{{ campaign|get_campaign_url }}" target="_blank">

                {% if campaign.title_es %}
                <p class="tittle">{{ campaign.title_es }}</p>
                {% else %}
                <p class="tittle">{{ campaign.title }}</p>
                {% endif %}
                <div class="col-lg-6">
                    <br>
                    <br>
                    {% if campaign.city and campaign.city.name %}
                    <b>CIUDAD: </b>{{ campaign.city.name }}
                    <br>
                    <br>
                    {% endif %}
                    {% if campaign.salary_low_range >= 0 %}
                    <p><b>SALARIO:</b> ${{ campaign.salary_low_range }} a ${{ campaign.salary_high_range }} </p>
                    {% endif %}
                </div>
                <div class="col-lg-6">
                    <br>
                    <br>
                    <div>
                        <img class="logo2" src="{% static 'business/img/logo-color-negro.png' %}">
                    </div>
                </div>

            </a>
        </div>
        <br>
        <br>
        {% endfor %}
    </div>
</div>
<script>
    window.pressed = function(){
        var a = document.getElementById('file');
        if(a.value == "")
        {
            fileLabel.innerHTML = "Selecciona un archivo";
        }
        else
        {
            var theSplit = a.value.split('\\');
            fileLabel.innerHTML = theSplit[theSplit.length-1];
        }
    };
</script>
<script>
    function on_login() {
    $("#overlay-login").css("display", "block");
    $("#login-form").css("display", "block");
    $("html").css("background-size", "cover");
    $("nav").css("margin-bottom", "40px");
    $("#login-form").animate({"marginLeft": '60%'}, 650,"swing");
    }

    function off_login() {
    $("#overlay-login").css("display", "none");
    $("#login-form").css("display", "none");
    $("nav").css("margin-bottom", "");
    $("#login-form").animate({marginLeft: '160%'});
    }

    function on_signup() {
    $("#overlay-signup").css("display", "block");
    $(".only-register-form").css("display", "block");
    $("html").css("background-size", "cover");
    $("nav").css("margin-bottom", "40px");

    if ($(window).width() < 769) {
        $(".only-register-form").animate({"marginLeft": 'auto'}, 650,"swing");
        $(".only-register-form").css("margin", "100px auto");
    }
    else {
        $(".only-register-form").animate({"marginLeft": '60%'}, 650,"swing");
    }
    $(".form-image").animate({"backgroundPosition": '86%'}, 690,"swing");
    }


    function off_signup() {
    $("#overlay-signup").css("display", "none");
    $(".only-register-form").css("display", "none");
    $("nav").css("margin-bottom", "");
    $(".only-register-form").animate({marginLeft: '160%'});
    $(".form-image").animate({"backgroundPosition": '186%'}, 1,"swing");
    }
</script>
<script>
    $(document).ready(function() {
        set_background("Start_BG-01.jpg", "main-section")
    });
</script>
<script>
    $( window ).resize(function() {
        set_background("Start_BG-01.jpg", "main-section")
    });
</script>
{% endblock %}