testing_webpage/api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^get_public_posts$', views.get_public_posts, name='get_public_posts'),
    url(r'^add_messages$', views.add_messages, name='add_messages'),
    url(r'^save_leads$', views.save_leads, name='save_leads'),

    # API v1
    url(r'^v1/register$', views.register, name='register'),
    url(r'^v1/get_work_areas', views.get_work_areas, name='get_work_areas'),
    url(r'^v1/get_cities$', views.get_cities, name='get_cities'),
    url(r'^v1/get_campaigns$', views.get_campaigns, name='get_campaigns'),

]

testing_webpage/business/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from business import views

app_name = 'business'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # LOGIN AND LOGOUT
    url(r'^login$', auth_views.login, {'template_name': 'business/login.html', 'extra_context': {'error_message': ''}}, name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': 'business:index'}, name='logout'),
    # CREATE CAMPAIGN
    url(r'^seleccion_gratis$', views.start, name='start'),
    url(r'^seleccion_gratis_enviar$', views.start_post, name='start_post'),
    # CREATE CAMPAIGN WHEN USER IS LOGGED
    url(r'^crear_enviar$', views.create_post, name='create_post'),
    # BUSINESS USER LOGGED
    url(r'^campañas/(?P<business_user_id>\d+)$', views.business_campaigns, name='business_campaigns'),
    url(r'^resumen/(?P<campaign_id>\d+)$', views.summary, name='summary'),
    url(r'^online_demo$', views.online_demo, name='online_demo'),
    url(r'^tablero_de_control/(?P<business_user_id>\d+)/(?P<campaign_id>\d+)/(?P<state_name>.*)/$', views.dashboard, name='dashboard'),
    url(r'^perfil_del_candidato/(?P<pk>\d+)$', views.candidate_profile, name='candidate_profile'),
    # CONTACT
    url(r'^contactanos$', views.contact_form, name='contact_form'),
    url(r'^contact_form_post$', views.contact_form_post, name='contact_form_post'),
    # START
    url(r'^get_work_area_requirement/(?P<work_area_id>\d+)$', views.get_work_area_requirement, name='get_work_area_requirement'),
    # PAYU
    url(r'payment_confirmation$', views.payment_confirmation, name='payment_confirmation'),


    url(r'^save_comments$', views.save_comments, name='save_comments'),
    # TODO: This search url should be deleted?
    url(r'^search$', views.search, name='search'),
    url(r'^results$', views.calculate_result, name='results'),
    url(r'^business_signup$', views.business_signup, name='business_signup'),
    url(r'^home$', views.home, name='home'),
    # TODO: Worst hack ever, replace for something like: \?id=[0-9]+
    url(r'^results/(?P<pk>\d+)$', views.render_result, name='render_result'),
    url(r'^plan/(?P<pk>\d+)$', views.plan, name='plan'),
]

'''
url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    auth_views.password_reset_confirm, name='password_reset_confirm'),
url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
'''

testing_webpage/dashboard/urls.py
from django.conf.urls import url

from . import views
from . import stats

app_name = 'dashboard'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # All tests
    url(r'^tests_list$', views.tests_list, name='tests_list'),

    # Campaign
    url(r'^campaign/(?P<campaign_id>\d+)$', views.edit_campaign_candidates, name='campaign'),
    url(r'^campaign/new$', views.new_campaign, name='new_campaign'),
    url(r'^campaign/create$', views.create_campaign, name='create_campaign'),
    url(r'^campaign/edit/(?P<pk>\d+)$', views.edit_campaign, name='edit_campaign'),
    url(r'^campaign/update_basic_properties$', views.update_basic_properties),
    url(r'^campaign/delete/(?P<pk>\d+)$', views.delete_campaign, name='delete_campaign'),
    url(r'^campaign/candidate/(?P<candidate_id>\d+)$', views.candidate_detail, name='candidate_detail'),

    # Campaign tests
    url(r'^campaign/(?P<pk>\d+)/add_test$', views.add_test),
    url(r'^campaign/(?P<pk>\d+)/delete_test$', views.delete_test),
    url(r'^campaign/(?P<pk>\d+)/tests$', views.tests),

    # Test
    # url(r'^', include('home.urls', namespace='home')),
    url(r'^test/(?P<pk>\d+)$', views.edit_test, name='test_edit'),
    url(r'^test/new$', views.new_test, name='new_test'),
    url(r'^test/save$', views.save_test, name='save_test'),
    url(r'^test/update/(?P<pk>\d+)$', views.update_test, name='update_test'),
    url(r'^test/delete_question$', views.delete_question, name='delete_question'),
    url(r'^test/delete_answer$', views.delete_answer, name='delete_answer'),
    url(r'^test/duplicate/(?P<pk>\d+)$', views.duplicate_test, name='duplicate_test'),

    # Bullets
    url(r'^campaign/(?P<pk>\d+)/bullets$', views.bullets),
    url(r'^campaign/update_bullets$', views.update_bullets),
    url(r'^campaign/delete_bullet$', views.delete_bullet),

    # Interview
    url(r'^edit_intro_video$', views.edit_intro_video, name='edit_intro_video'),
    url(r'^campaign/interview/(?P<pk>\d+)$', views.interview, name='interview'),
    url(r'^campaign/check_interview$', views.check_interview, name='check_interview'),
    url(r'^campaign/interview/create_interview_question$', views.create_interview_question, name='create_interview_question'),
    url(r'^campaign/interview/update_interview_question$', views.update_interview_question, name='update_interview_question'),
    url(r'^campaign/interview/delete_interview_question$', views.delete_interview_question, name='delete_interview_question'),

    # Auto messenger
    url(r'^send_new_contacts$', views.send_new_contacts, name='send_new_contacts'),
    url(r'^send_messages$', views.send_messages, name='send_messages'),

    # stats
    url(r'^candidates_stats$', stats.candidates_count, name='candidates_stats'),
    url(r'^campaign_stats$', stats.campaign_count, name='campaign_stats'),
    url(r'^number_of_forecasts$', stats.number_of_forecasts, name='number_of_forecasts'),
    url(r'^positive_forecasts$', stats.positive_forecasts, name='positive_forecasts'),
    url(r'^negative_forecasts$', stats.negative_forecasts, name='negative_forecasts'),

]

testing_webpage/business/views.py
import os
import json
from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'testing_webpage.testing_webpage.settings')
application = get_wsgi_application()

import smtplib
import hashlib
from datetime import datetime
from django.contrib.auth.decorators import login_required
from ipware.ip import get_ip
from django.shortcuts import render, redirect
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import login, authenticate
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.forms import AuthenticationForm
from django.utils import formats
from django.http import HttpResponseBadRequest, HttpResponse, JsonResponse
from decouple import config
from django.db import models
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

import common
import business
import beta_invite
from business import search_module
from beta_invite.util import email_sender
from business import constants as cts
from beta_invite.models import User, WorkArea, EmailType, Campaign, Test, Price, CampaignState
from business.models import Plan, Contact, Search, BusinessUser, Company
from beta_invite.models import Requirement
from business.custom_user_creation_form import CustomUserCreationForm
from dashboard import campaign_module
from dashboard.models import Candidate, BusinessState, Comment
from business import dashboard_module
from testing_webpage.models import BusinessUserPendingEmail
from api.models import PublicPost


TAX = 0.19
DEFAULT_BASE_PRICE = 0
INVALID_WORK_AREAS = [8, 14, 17]


def index(request):
    """
    will render and have the same view as /beta_invite except for message customization.
    Args:
        request: Object
    Returns: Save
    """

    ip = get_ip(request)

    business.models.Visitor(ip=ip).save()
    return render(request, cts.INDEX_VIEW_PATH, {'error_message': ''})


def search(request):
    """
    will render the search view.
    Args:
        request: Object
    Returns: Save
    """

    ip = get_ip(request)
    action_url = '/business/results'
    countries, cities, education, professions = beta_invite.views.get_drop_down_values(request.LANGUAGE_CODE)

    business.models.Visitor(ip=ip).save()
    return render(request, cts.SEARCH_VIEW_PATH, {'main_message': _("Discover amazing people"),
                                                  'secondary_message': _("We search millions of profiles and find the ones that best suit your business"),
                                                  'action_url': action_url,
                                                  'countries': countries,
                                                  'education': education,
                                                  'professions': professions,
                                                  })


def calculate_result(request):
    """
    Args:
        request: Request object
    Returns: renders results.html view.
    """

    user_ids = search_module.get_common_search_info(request)

    search_obj = Search(ip=get_ip(request),
                        country=None,
                        education=None,
                        profession=None,
                        experience=None,
                        text=search_module.get_text_from_request(request),
                        user_ids=user_ids, )

    search_obj.save()

    return redirect('results/{id}'.format(id=search_obj.id))


def render_result(request, pk):
    """
    Gets a stored search back to life.
    Args:
        request: HTTP request.
        pk: primary key of a search
    Returns: Renders search results.
    """

    search_obj = Search.objects.get(pk=pk)
    users = [User.objects.get(pk=u_id) for u_id in search_obj.user_ids]
    params = {'main_message': _("Discover amazing people"),
              'secondary_message': _("We search millions of profiles and find the ones that best suit your business"),
              'users': users}

    return render(request, cts.RESULTS_VIEW_PATH, params)


def translate_message(plan, language_code):
    """
    Args:
        plan: Object of class Plan.
        language_code:
    Returns:
    """
    if 'es' in language_code:
        plan.message = plan.message_es

    return plan


def get_plan(request):
    """
    Args:
        request: HTTP request
    Returns: Returns a Plan obj
    """

    plan_id = request.POST.get('plan_id')
    try:
        plan = Plan.objects.get(pk=plan_id)
    except ObjectDoesNotExist:
        # Gets the default plan.
        plan = Plan.objects.get(pk=4)

    return translate_message(plan, request.LANGUAGE_CODE)


def send_signup_emails(business_user, language_code, campaign):

    if campaign is None:
        body_filename = 'business_signup_notification_email_body'
        body_input = 'business_signup_email_body'
    else:
        body_filename = 'business_start_signup_notification_email_body'
        body_input = 'business_start_signup_email_body'

    # TODO: make producer consumer work!
    """
    PendingEmail.add_to_queue(candidates=business_user,
                              language_code=language_code,
                              body_input=body_input,
                              subject=_('Welcome to PeakU'),
                              email_type=email_type)
    """

    try:

        BusinessUserPendingEmail.add_to_queue(business_users=business_user,
                                              language_code=language_code,
                                              body_input=body_input,
                                              subject=_('Welcome to PeakU'),
                                              email_type=EmailType.objects.get(name='business welcome'))
        email_sender.send_internal(contact=business_user,
                                   language_code=language_code,
                                   body_filename=body_filename,
                                   subject='Business User acaba de registrarse!!!',
                                   campaign=campaign)
    except (smtplib.SMTPRecipientsRefused, smtplib.SMTPAuthenticationError, UnicodeEncodeError) as e:
        pass


def first_sign_in(signup_form, campaign, request):
    """
    This method is used to do stuff after validating signup-data. Also logs in.
    Args:
        signup_form: Form obj
        request: HTTP obj
        campaign: campaign object
    Returns: None, first auth and sign-in, saves objects
    """

    signup_form.save()
    username = signup_form.cleaned_data.get('username')
    password = signup_form.cleaned_data.get('password1')

    # Creates a Authentication user
    auth_user = authenticate(username=username,
                             password=password)

    company = Company(name=request.POST.get('company'))
    company.save()

    # New BusinessUser pointing to the AuthUser
    business_user = business.models.BusinessUser(name=request.POST.get('name'),
                                                 company=company,
                                                 email=request.POST.get('username'),
                                                 phone=request.POST.get('phone'),
                                                 ip=get_ip(request),
                                                 plan=get_plan(request),
                                                 auth_user=auth_user)

    business_user.save()

    login(request, auth_user)

    send_signup_emails(business_user, request.LANGUAGE_CODE, campaign)

    return business_user


def get_business_user(request):
    """
    Given a request that has the AuthUser.id will get the BusinessUser
    Args:
        request: HTTP request object.
    Returns: A BusinessUser object.
    """
    return BusinessUser.objects.get(auth_user_id=request.user.id)


def get_first_error_message(form):
    """
    :param form: AuthenticationForm or UserCreationForm
    :return: str with first error_message
    """
    error_messages = [m[0] for m in form.errors.values()]
    if len(error_messages) > 0:  # Takes first element from the errors dictionary
        error_message = error_messages[0]
    else:
        error_message = 'unknown error'
    return error_message


def simple_login_and_business_user(login_form, request):
    """
    :param login_form: a AuthenticationForm object
    :param request: HTTP
    :return: BusinessUser obj
    """
    username = login_form.cleaned_data.get('username')
    password = login_form.cleaned_data.get('password')

    # Creates a Authentication user
    auth_user = authenticate(username=username,
                             password=password)

    login(request, auth_user)

    return BusinessUser.objects.get(auth_user=auth_user)


def home(request):
    """
    Leads to Dashboard view.
    Args:
        request: HTTP request.
    Returns: displays all offers of a business
    """

    login_form = AuthenticationForm(data=request.POST)

    # TODO: generalize to set of blocked emails.
    if login_form.is_valid():

        business_user = simple_login_and_business_user(login_form, request)
        if request.POST.get('username') == 'admin@peaku.co':
            return redirect(common.get_host()+'/dashboard')
        else:
            return redirect('campañas/{}'.format(business_user.pk))

    else:
        error_message = get_first_error_message(login_form)
        return render(request, cts.BUSINESS_LOGIN, {'error_message': error_message})


def send_contact_emails(contact, language_code):

    try:
        email_sender.send(objects=contact,
                          language_code=language_code,
                          body_input='business_contact_email_body',
                          subject=_('Welcome to PeakU'))
        email_sender.send_internal(contact=contact,
                                   language_code=language_code,
                                   body_filename='contact_notification_email_body',

testing_webpage/business/templates/business/business_campaigns.html
{% extends 'white_header_base.html'%}
{% load static %}
{% load i18n %}
{% load app_filters %}
{% load compress %}
{% block title %}Selección, contratación y reclutamiento de personal{% endblock %}
{% block extra_meta %}
    <meta name="description"  content="Publica y comparte ofertas laborales, realiza pruebas relacionadas al cargo y selecciona al mejor personal. Podrás buscar, filtrar y comunícarte fácilmente con los candidatos en todas las etapas del proceso." />
    <meta name="keywords" content="cazatalentos, selección de personal, reclutamiento personal, contratacion personal, selección personal, agencias, reclutamiento, reclutamiento empleados, busqueda personal, preselección personal, headhunter, agencia empleo" />
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'business/css/business_campaigns.css' %}">
{% endblock %}

{% block content %}
    <form class="content" action="{% url 'business:start' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="business_user_id" value="{{ business_user_id }}" />
    </form>
    <h1 style="text-align:center; margin:50px 0px">{% trans "Campaigns" %}</h1>
        <div style="min-height: 500px;">
        {% for campaign in campaigns %}
            <div class="campaign-div">
                <div class="row">
                    <p class="tittle">{{ campaign.title_es }}</p>
                    <div class="col-lg-12">
                        <a href="{{ campaign|get_campaign_url }}" target="_blank"><b>Ver la oferta que ven los candidatos</b></a>
                    <br>
                    <br>
                        <a href="{% url 'business:summary' campaign_id=campaign.pk %}"><b>TABLERO DE CONTROL</b></a>
                    <br>
                    <br>
                    <p><b>EMPRESA:</b> {{ campaign|get_business_user_company_with_campaign }}</p>
                    <p><b>REPRESENTANTE:</b> {{ campaign|get_business_user_name_with_campaign }}</p>
                    <p><b>ESTADO:</b> {{ campaign.state.name_es }}</p>
                    <p><b>FECHA DE CREACIÓN:</b> {{ campaign.local_date }}</p>
                    {% if campaign.salary_low_range >= 0 %}
                        <p><b>SALARIO:</b> ${{ campaign.salary_low_range }} a ${{ campaign.salary_high_range }} </p>
                    {% endif %}
                    {% if campaign.free_trial == True and campaign.state.name_es != 'Activa' and campaign.base != 0 %}
                        {% if campaign.salary_low_range >= 0 and campaign.work_area.pk not in invalid_work_areas %}
                            <form method="post" action="{{ action_url }}" accept-charset="UTF-8">
                                <!--PAYMENT GENERIC INFO-->
                                <input name="ApiKey" type="hidden" value="{{ apikey }}"/>
                                <input name="merchantId" type="hidden" value="{{ merchant_id }}"/>
                                <input name="accountId" type="hidden" value="{{ account_id }}"/>
                                <input name="currency" type="hidden" value="{{ currency }}"/>
                                <input name="test" type="hidden" value="{{ test }}"/>
                                <input name="description" type="hidden" value="{{ description }}"/>
                                <!--PAYMENT DYNAMIC INFO-->
                                <input name="buyerFullName" type="hidden" value="{{ buyer_name }}"/>
                                <input name="buyerEmail" type="hidden" value="{{ buyer_email }}"/>
                                <input name="referenceCode" type="hidden" value="{{ campaign.reference_code }}"/>
                                <input name="amount" type="hidden" value="{{ campaign.amount }}"/>
                                <input name="tax" type="hidden" value="{{ campaign.tax }}"/>
                                <input name="taxReturnBase" type="hidden" value="{{ campaign.base }}"/>
                                <input name="signature"  type="hidden" value="{{ campaign.signature }}"/>
                                <!--RESPONSE URL VISIBLE-->
                                <input name="responseUrl" type="hidden"  value="{{ response_url }}{{ campaign.pk }}" >
                                <!--CONFIRMATION URL NOT VISIBLE-->
                                <input name="confirmationUrl" type="hidden"  value="{{ confirmation_url }}" >
                                <!--EXTRA INFO-->
                                <input name="extra1" type="hidden"  value="{{ campaign.pk }}" >
                                <input type="submit" class="submit-button-strong" value="Activar Premium"/>
                                <!--BUTTON
                                <input type="image" border="0" alt="" src="http://www.payulatam.com/img-secure-2015/boton_pagar_pequeno.png" onClick="this.form.urlOrigen.value = window.location.href;"/>
                               <input name="buttonId" type="hidden" value="uHXTlFj9y4bMS9srB5O11WLUxNGBJ1tcne4nSsYZt/7VQHZZ7X8vCg=="/>
                                <input name="buttonType" value="SIMPLE" type="hidden"/>-->
                            </form>
                        {% else %}
                            <p>Para activar esta campaña debe comunicarse con nosotros</p>
                        {% endif %}
                    {% endif %}
                </div>
                </div>
            </div>
        {% endfor %}
        </div>
{% endblock %}

testing_webpage/business/templates/business/contact.html
{% extends 'white_header_base.html'%}
{% load static %}
{% load i18n %}
{% load app_filters %}
{% load compress %}
{% block extra_meta %}
<meta name="description" content="Resolvemos tus preguntas sobre nuestras ofertas de empleo y el procesos de selección y reclutamiento de personal para empresas en Colombia, Chile, Ecuador, Perú y Argentina." />
<meta name="keywords" content="cazatalentos, selección de personal, reclutamiento personal, contratacion personal, selección personal, agencias, reclutamiento, servicio de empleo , empleo, ofertas de empleo , headhunter, agencia empleo" />
{% endblock %}
{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'business/css/contact_form.css' %}">
{% endblock %}
{% block content %}
<section class="section-container">
    <div class="row">
        <div class="col-lg-12">
            <div class="only-register-form">
                <div class="title">
                    <br>
                    <h2 style="font-size:35px; margin-top:10px; color:white; ">{{ main_message }}</h2>
					<b style="font-weight:500; color:white; text-transform: uppercase;">{% trans "Thanks for reaching out!" %}</b>
					<br>
					<b style="font-weight:400; color:white; font-size:18px">{% trans "We will contact you soon" %}</b>
					<br>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

testing_webpage/business/templates/business/contact_form.html
{% extends 'white_header_base.html'%}
{% load static %}
{% load i18n %}
{% load app_filters %}
{% load compress %}
{% block extra_meta %}
    <meta name="description" content="Resolvemos tus preguntas sobre nuestras ofertas de empleo y el procesos de selección y reclutamiento de personal para empresas en Colombia, Chile, Ecuador, Perú y Argentina." />
    <meta name="keywords" content="cazatalentos, selección de personal, reclutamiento personal, contratacion personal, selección personal, agencias, reclutamiento, servicio de empleo , empleo, ofertas de empleo , headhunter, agencia empleo" />
{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'business/css/contact_form.css' %}">
{% endblock %}
{% block content %}
    <section class="section-container">
        <div class="row">
            <div class="col-lg-12">
                <form class="only-register-form" action="{% url 'business:contact_form_post' %}" method="post">
                    {% csrf_token %}

                    <input class="form-text" type="text" name="name"
				        placeholder="{% trans 'Your Full Name' %}" required="required" pattern="[A-Za-z\sÁÉÍÓÚáéíóúÑñÜü]{1,200}">

                    <input class="form-text" type="email" name="email"
                         placeholder="{% trans 'Your email' %}" required="required">

                    <input class="form-text" type="tel" name="phone"
                         placeholder="{% trans 'Your phone (optional)' %}">

                    <textarea class="form-text-area" name="message" rows="10" cols="20" autocomplete="off" maxlength="500" placeholder="{% trans 'Add a message (optional)' %}"></textarea>

                    <input class="form-submit" type="submit" value="{% trans 'Sure!' %}">
                </form>
            </div>
        </div>
    </section>
{% endblock %}

testing_webpage/business/templates/business/dashboard_column.html
{% load static %}

<div class="line"></div>
<div id="{{ state_name }}" class="internal-div">
{% for candidate in candidate_list %}
    <div class="candidate-div">
        {% include "business/candidate_for_campaign.html" with candidate=candidate %}
    </div>
{% endfor %}
</div>

testing_webpage/business/templates/business/login.html
{% extends 'base.html'%}
{% load static %}
{% load i18n %}
{% block title %}PeakU - Login{% endblock %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="welcome-section" id="top" >
    <div style="margin-top:-100px;">
        <h1 align="center" style="color:var(--brochure-blue)">{% trans "Log in to our platform" %}</h1>
        <div class="container" style="margin-top:50px;">

                <form method="post" style="text-align:center; margin-top:0px;" action="{% url 'business:home' %}" enctype="multipart/form-data">

                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
                {% trans "Your email" as email_placeholder %}
                <input style="font-family:Raleway; padding-left: 15px; font-size: 14px; height: 40px; margin-top:15px;
                    border:solid 2px var(--brochure-blue); background-color:white; width: 250px;" id="username" type="email" name="username"
                    placeholder="{{ email_placeholder }}" required="required">
                <br>
                {% trans "Enter your password" as password1_placeholder %}
                <input style="font-family:Raleway; padding-left: 15px; font-size: 14px; height: 40px; margin-top:15px;
                    border:solid 2px var(--brochure-blue); background-color:white; width: 250px;" id="password" type="password" name="password"
                    placeholder="{{ password1_placeholder }}" required="required">
                <br>
                {% trans "Log In" as submit_value %}
                <input style="height: 44px; border:  2px black; background:var(--brochure-blue); color:white; text-align:center;
                    width: 81px; font-size: 16px; width: 255px; margin-bottom:20px; margin-top:15px; cursor:pointer;" type="submit" value="{{ submit_value }}">
                <br>
                <!--<a style="text-align:center" href="{% url 'password_reset' %}">¿Olvidaste la contraseña?</a>-->
                <br>
                <br>
            </form>
        </div>
    </div>
    <!-- ARROW SCROLL-->
    <div class="arrow">
    </div>
    <!-- /ARROW SCROLL -->
    <div class="container">
    </div>
</div>
<!-- any incoming error_message will print as an alert.-->
<script>
    {% if error_message %}
        alert("{{ error_message }}");
    {% endif %}
</script>
{% endblock %}

testing_webpage/business/templates/business/login_buttons.html
{% load i18n %}

{% if user.is_authenticated %}

    {% trans "Log Out" as logout_value %}
    <div align="right" style="margin-top:15px; margin-right:15px; cursor:pointer;">
        <form style="cursor:pointer;" action="{% url 'business:logout' %}">
            <input style="height: 34px; border: solid 0px white; background:#F8E676; color:black; text-align:center;
                   font-size: 16px; width: 110px; cursor:pointer;" type="submit" value="{{ logout_value }}">
        </form>
    </div>

{% else %}

    <div style="margin-top:15px; margin-right:15px; cursor:pointer;">

        {% trans "Log In" as login_value %}
        <form style="text-align: right; cursor:pointer;" action="{% url 'business:login' %}">
            <input style="height: 34px; border: solid 0px white; background:rgba(255, 255, 255, .0); color:#F8E676; text-align:center;
                   font-size: 16px; width: 110px; cursor:pointer;" type="submit" value="{{ login_value }}">
        </form>

    </div>
{% endif %}

testing_webpage/business/templates/business/plan.html
{% extends 'base.html'%}
{% load i18n %}
{% load static %}


{% block title %}{{ plan.name }}{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'business/css/plan.css' %}">
{% endblock %}


{% block content %}

    <img src="{% static 'business/img/plan_2.jpg' %}"
         srcset="{% static 'business/img/plan_2@2x.jpg' %} 2x,
                 {% static 'business/img/plan_2@3x.jpg' %} 3x"
         class="background-people" >

    <img src="{% static 'business/img/plan_2_mobile.jpg' %}"
         srcset="{% static 'business/img/plan_2_mobile@2x.jpg' %} 2x,
                 {% static 'business/img/plan_2_mobile@3x.jpg' %} 3x"
         class="background-people-mobile" >

    <h1 class="main-title" >{{ plan.name }}</h1>

    <div id="text-white-rectangle">
        <p id="description-text" >{{ plan.explanation }}</p>

        <a href="{% url 'business:start' %}">
            <form method="get">
                <input class="form-submit" type="button" value="{% trans 'I want it' %}">
            </form>
        </a>
    </div>

    <section id="section-container-plan">

        <h3 class="title-blue">{% trans "Characteristics:" %}</h3>
        <p class="paragraph">{% trans "Creation of job post for your public campaign" %}</p>
        <p class="paragraph">{% trans "Publication in job boards, social networks and in database. High volume of candidates" %}</p>
        <p class="paragraph">{% trans "We guarantee relevant candidates" %}</p>
        <p class="paragraph">{% trans "Selection of resumes according to requirements, we recommend the best 10 candidates" %}</p>
        <p class="paragraph">{% trans "Access to the control panel to see candidates, applicants and detailed information of the tests and their answers" %}</p>

        {% if plan.id == 2 %}
            <p class="paragraph">{% trans "Google type selection process" %}</p>
            <p class="paragraph">{% trans "We continue with the process until you achieve a successful contracting" %}</p>
        {% endif %}

        {% if plan.id == 3 %}
            <p class="paragraph">{% trans "Google type selection process" %}</p>
            <p class="paragraph">{% trans "We find difficult profiles quickly" %}</p>
            <p class="paragraph">{% trans "We continue with the process until you achieve a successful contracting" %}</p>
        {% endif %}
    </section>
{% endblock %}