testing_webpage/api/urls.py
from django.conf.urls import url

from . import views

app_name = 'api'

urlpatterns = [
    url(r'^get_public_posts$', views.get_public_posts, name='get_public_posts'),
    url(r'^add_messages$', views.add_messages, name='add_messages'),
    url(r'^save_leads$', views.save_leads, name='save_leads'),

    # API v1
    url(r'^v1/register$', views.register, name='register'),
    url(r'^v1/get_work_areas', views.get_work_areas, name='get_work_areas'),
    url(r'^v1/get_cities$', views.get_cities, name='get_cities'),
    url(r'^v1/get_campaigns$', views.get_campaigns, name='get_campaigns'),

]

testing_webpage/beta_invite/urls.py
from django.conf.urls import url

from . import views

app_name = 'beta_invite'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^registro$', views.register, name='register'),
    url(r'^pruebas$', views.tests, name='tests'),
    url(r'^test_result$', views.get_test_result, name='test_result'),
    url(r'^add_cv$', views.add_cv, name='add_cv'),
    url(r'^add_cv_changes$', views.add_cv_changes),
    url(r'^additional_info$', views.additional_info, name='additional_info'),
    url(r'^save_partial_additional_info$', views.save_partial_additional_info, name='save_partial_additional_info'),
    url(r'^active_campaigns', views.active_campaigns, name='active_campaigns'),
    url(r'^security_politics', views.security_politics, name='security_politics'),
]

testing_webpage/business/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from business import views

app_name = 'business'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # LOGIN AND LOGOUT
    url(r'^login$', auth_views.login, {'template_name': 'business/login.html', 'extra_context': {'error_message': ''}}, name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': 'business:index'}, name='logout'),
    # CREATE CAMPAIGN
    url(r'^seleccion_gratis$', views.start, name='start'),
    url(r'^seleccion_gratis_enviar$', views.start_post, name='start_post'),
    # CREATE CAMPAIGN WHEN USER IS LOGGED
    url(r'^crear_enviar$', views.create_post, name='create_post'),
    # BUSINESS USER LOGGED
    url(r'^campañas/(?P<business_user_id>\d+)$', views.business_campaigns, name='business_campaigns'),
    url(r'^resumen/(?P<campaign_id>\d+)$', views.summary, name='summary'),
    url(r'^online_demo$', views.online_demo, name='online_demo'),
    url(r'^tablero_de_control/(?P<business_user_id>\d+)/(?P<campaign_id>\d+)/(?P<state_name>.*)/$', views.dashboard, name='dashboard'),
    url(r'^perfil_del_candidato/(?P<pk>\d+)$', views.candidate_profile, name='candidate_profile'),
    # CONTACT
    url(r'^contactanos$', views.contact_form, name='contact_form'),
    url(r'^contact_form_post$', views.contact_form_post, name='contact_form_post'),
    # START
    url(r'^get_work_area_requirement/(?P<work_area_id>\d+)$', views.get_work_area_requirement, name='get_work_area_requirement'),
    # PAYU
    url(r'payment_confirmation$', views.payment_confirmation, name='payment_confirmation'),


    url(r'^save_comments$', views.save_comments, name='save_comments'),
    # TODO: This search url should be deleted?
    url(r'^search$', views.search, name='search'),
    url(r'^results$', views.calculate_result, name='results'),
    url(r'^business_signup$', views.business_signup, name='business_signup'),
    url(r'^home$', views.home, name='home'),
    # TODO: Worst hack ever, replace for something like: \?id=[0-9]+
    url(r'^results/(?P<pk>\d+)$', views.render_result, name='render_result'),
    url(r'^plan/(?P<pk>\d+)$', views.plan, name='plan'),
]

'''
url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    auth_views.password_reset_confirm, name='password_reset_confirm'),
url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
'''

testing_webpage/testing_webpage/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^trabajos$', views.jobs, name='index'),
    url('^', include('django.contrib.auth.urls')),
    url(r'^servicio_de_empleo/', include('beta_invite.urls')),
    url(r'^seleccion_de_personal/', include('business.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^admin/', admin.site.urls)
]

urlpatterns += i18n_patterns(
    url(r'^staffing$', views.index, name='index'),
    url(r'^sitemap.xml$', views.sitemap, name='sitemap'),
    url(r'^BingSiteAuth.xml$', views.bing_site_auth, name='BingSiteAuth'),
    url(r'^robots.txt$', views.robots, name='robots')
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testing_webpage/testing_webpage/models.py
from django.db import models
from picklefield.fields import PickledObjectField


from beta_invite.models import EmailType
from business.models import BusinessUser
from dashboard.models import Candidate


class CandidateEmailSent(models.Model):

    email_type = models.ForeignKey(EmailType, on_delete=models.DO_NOTHING)
    candidate = models.ForeignKey(Candidate, on_delete=models.DO_NOTHING, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'id={0}, candidate_id={1}, email_type={2}'.format(self.pk, self.candidate.id, self.email_type)

    # adds custom table name
    class Meta:
        db_table = 'candidate_emails_sent'


class BusinessUserEmailSent(models.Model):

    email_type = models.ForeignKey(EmailType, on_delete=models.DO_NOTHING)
    business_user = models.ForeignKey(BusinessUser, on_delete=models.DO_NOTHING, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'id={0}, candidate_id={1}, email_type={2}'.format(self.pk, self.business_user.id, self.email_type)

    # adds custom table name
    class Meta:
        db_table = 'business_user_emails_sent'


class CandidatePendingEmail(models.Model):

    candidates = models.ManyToManyField(Candidate)
    language_code = models.CharField(max_length=3)
    body_input = models.CharField(max_length=10000)
    subject = models.CharField(max_length=200)
    email_type = models.ForeignKey(EmailType, on_delete=models.DO_NOTHING)

    # optional
    with_localization = models.BooleanField(default=True)
    body_is_filename = models.BooleanField(default=True)
    override_dict = PickledObjectField(default={})

    # internal
    sent = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'id={0}'.format(self.pk)

    @staticmethod
    def add_to_queue(**kwargs):

        candidates = kwargs.pop('candidates', None)

        email = CandidatePendingEmail(**kwargs)
        email.save()
        email.save_candidates(candidates)

    def save_candidates(self, candidates):
        """
        Can __init__ with 1 candidate or a list  of candidates.
        :param candidates:
        :return:
        """
        if candidates and type(candidates) != list:
            candidates = [candidates]

        self.candidates = candidates
        self.save()

    # adds custom table name
    class Meta:
        db_table = 'candidate_pending_emails'


class BusinessUserPendingEmail(models.Model):

    business_users = models.ManyToManyField(BusinessUser)
    language_code = models.CharField(max_length=3)
    body_input = models.CharField(max_length=10000)
    subject = models.CharField(max_length=200)
    email_type = models.ForeignKey(EmailType, on_delete=models.DO_NOTHING, null=True)

    # optional
    with_localization = models.BooleanField(default=True)
    body_is_filename = models.BooleanField(default=True)
    override_dict = PickledObjectField(default={})

    # internal
    sent = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'id={0}'.format(self.pk)

    @staticmethod
    def add_to_queue(**kwargs):

        business_users = kwargs.pop('business_users', None)

        email = BusinessUserPendingEmail(**kwargs)
        email.save()
        email.save_business_users(business_users)

    def save_business_users(self, business_users):
        """
        Can __init__ with 1 business_user or a list of business_users.
        :param business_users:
        :return:
        """
        if business_users and type(business_users) != list:
            business_users = [business_users]

        self.business_users = business_users
        self.save()

    # adds custom table name
    class Meta:
        db_table = 'business_user_pending_emails'

testing_webpage/testing_webpage/views.py
from django.shortcuts import render
from testing_webpage import constants as cts
from beta_invite.models import Campaign
from django.db.models import Q


def index(request):
    """
    will render the intro
    """
    return render(request, cts.INDEX_VIEW_PATH)


def sitemap(request):
    return render(request, 'testing_webpage/sitemap.xml', {}, content_type="application/xhtml+xml")


def bing_site_auth(request):
    return render(request, 'testing_webpage/BingSiteAuth.xml', {}, content_type="application/xhtml+xml")


def robots(request):
    return render(request, 'testing_webpage/robots.txt', {}, content_type="application/xhtml+txt")


def jobs(request):
    segment_code = request.GET.get('segment_code')
    if segment_code is None:  # if code not found will return everything
        return render(request, cts.JOBS_VIEW_PATH,
                      {'active_campaigns': Campaign.objects.filter(~Q(title_es=None),
                                                                   state__code__in=['I', 'A'],
                                                                   removed=False)})
    else:
        return render(request, cts.JOBS_VIEW_PATH,
                      {'active_campaigns': Campaign.objects.filter(~Q(title_es=None),
                                                                   state__code__in=['I', 'A'], removed=False,
                                                                   work_area__segment__code=segment_code
                                                                   )})

testing_webpage/testing_webpage/templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
{% load app_filters %}
{% load compress %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <!------------------------------------------META------------------------------------------------------------------->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <!--Meta description and keywords for each template-->
    {% block extra_meta %}{% endblock %}
    <!------------------------------------------BASE CSS--------------------------------------------------------------->
    <!--Latest compiled and minified bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!--Favicon-->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'testing_webpage/favicon.ico/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="16x16" href="{% static 'testing_webpage/favicon.ico/favicon-16.png' %}">
    <link rel="apple-touch-icon" sizes="32x32" href="{% static 'testing_webpage/favicon.ico/favicon-32.png' %}">
    <link rel="apple-touch-icon" sizes="64x64" href="{% static 'testing_webpage/favicon.ico/favicon-64.png' %}">
    <!--Our css-->
    <link rel="stylesheet" type="text/css" href="{% static 'testing_webpage/css/base.css' %}">
    <!------------------------------------------EXTRA CSS-------------------------------------------------------------->
    {% block header_base_css %}{% endblock %}
    {% block extra_css %}{% endblock %}
    <!------------------------------------------BASE JS---------------------------------------------------------------->
    <!-- Latest jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!--Latest compiled bootstrap javaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!--Header topnav-->
    <script>
        function myFunction() {
            var x = document.getElementById("myTopnav");
            if (x.className === "topnav") {
                x.className += " responsive";
            } else {
                x.className = "topnav";
            }
        }
    </script>
    <!--Smartlook for record the users interactions-->
    <script id="Heat-map" type="text/javascript">
        window.smartlook||(function(d) {
        var o=smartlook=function(){ o.api.push(arguments)},h=d.getElementsByTagName('head')[0];
        var c=d.createElement('script');o.api=new Array();c.async=true;c.type='text/javascript';
        c.charset='utf-8';c.src='https://rec.smartlook.com/recorder.js';h.appendChild(c);
        })(document);
        smartlook('init', '495c7bd6807a0ab2c17ade2e03cac13bab9f1b84');
    </script>
    <!--Google analytics-->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110863941-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-110863941-1');
    </script>
    <!--Tawk chat-->
    {% if 'seleccion_de_personal' in request.path %}
        <script type="text/javascript">
            var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
            (function(){
            var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
            s1.async=true;
            s1.src='https://embed.tawk.to/5a5d24064b401e45400c1ca0/default';
            s1.charset='UTF-8';
            s1.setAttribute('crossorigin','*');
            s0.parentNode.insertBefore(s1,s0);
            })();
        </script>
    {% endif %}
    <!--Facebook pixel code for candidates campaigns-->
    {% if 'servicio_de_empleo' in request.path %}
        <script>
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window,document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '723083944567694');
            fbq('track', 'PageView');
        </script>
        <noscript>
            <img height="1" width="1" src="https://www.facebook.com/tr?id=723083944567694&ev=PageView&noscript=1"/>
        </noscript>
    {% endif %}
    <!--Our js-->
    <!------------------------------------------EXTRA JS--------------------------------------------------------------->
    {% block header_base_js %}{% endblock %}
    {% block extra_js %}{% endblock %}
<body>
    <!------------------------------------------SPECIFIC HEADER CONTENT------------------------------------------------>
    <header>{% block header %}{% endblock %}</header>
    <!------------------------------------------EACH TEMPLATE CONTENT-------------------------------------------------->
    {% block content %}{% endblock %}
    <!------------------------------------------FOOTER----------------------------------------------------------------->
    <footer class="container-fluid">
        <div class="row footer-navigation">
            <div class="col-lg-5 navfooter">
                <ul>
                    <div>
                        <li><a href="#">{% trans 'Us' %}</a></li>
                        {% if 'seleccion_de_personal' in request.path %}
                            <li><a href="{% url 'business:contact_form' %}">{% trans 'Contact Us' %}</a></li>
                        {% else %}
                            <li><a href="{% url 'beta_invite:index' %}">{% trans 'Contact Us' %}</a></li>
                        {% endif %}
                        <li><a href="{% url 'beta_invite:index' %}">{% trans 'Candidates' %}</a></li>
                    </div>
                </ul>
            </div>
            <div class="col-lg-2 social">
                <a href="https://www.linkedin.com/company-beta/16241506/" target="_blank"><img src="{% static 'business/img/linkedin.png' %}"></a>
                <a href="https://www.facebook.com/PeakU-Latam-1916685895214519/?ref=aymt_homepage_panel" target="_blank">
                <img src="{% static 'business/img/facebook.png' %}"></a>
                <a href="https://www.instagram.com/peaku_latam" target="_blank"><img src="{% static 'business/img/instagram.png' %}"></a>
                <a href="#" target="_blank"><img src="{% static 'business/img/twitter.png' %}"></a>
            </div>
            <div class="col-lg-5 navfootercontact">
                <div class="row">
                    <div class="col-lg-4 logo-white"><a href="#"><img src="{% static 'business/img/logo-white.png' %}"></a></div>
                    <div class="col-lg-8 contact-data">
                        contacto@peaku.co<br>
                        +57 311 6109340<br>
                        Colombia
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="copyright">{% trans 'Copyright 2018 © PeakU. All rights reserved.' %}</div>
        </div>
    </footer>
</body>
</html>

testing_webpage/testing_webpage/templates/no_header_base.html
{% extends 'base.html'%}
{% load i18n %}
{% load static %}
{% load app_filters %}
{% load compress %}
{% block header_base_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'testing_webpage/css/no_header_base.css' %}">
{% endblock %}
{% block header %}
    <nav class="row" style="margin-right: 0px; margin-left: 0px;" id="myTopnav">
        <div class="col-lg-2 col-md-2 col-sm-2">
            <a href="/staffing">
                <img id="logo" src="{% static 'business/img/logo-color.png' %}" width="110px">
            </a>
        </div>
        <div class="col-lg-10 col-md-10 col-sm-10 push10">
            <ul class="topnav-list">
                {% if 'seleccion_de_personal' in request.path %}
                    <li id="candidates-button"><a id="option1" href="{% url 'index' %}">{% trans 'Candidates' %}</a></li>
                    <li id="contact-us-button"><a id="option2" href="{% url 'business:contact_form' %}">{% trans 'Contact Us' %}</a></li>
                    {% if user.is_authenticated %}
                        <li><a class="button-user" href="{% url 'business:business_campaigns' user|get_business_user_id_from_auth_user %}">{% trans 'My campaigns' %}</a></li>
                        <li><a class="button-user logout" role="button" href="{% url 'business:logout' %}">{% trans 'Sign off' %}</a></li>
                    {% else %}
                        <li id="login-button"><a class="button-user" role="button" onclick="on_login()">{% trans 'Sign in' %}</a></li>
                        {% if not 'seleccion_gratis' in request.path %}
                            <li id="register-button"><a class="button-user" role="button" onclick="on_signup()">{% trans 'Sign up' %}</a></li>
                        {% endif %}
                    {% endif %}
                {% else %}
                    {% if user.is_authenticated %}
                        <li id="companies-button"><a id="option1" href="{% url 'business:business_campaigns' user|get_business_user_id_from_auth_user %}" class="button-user" role="button">{% trans 'Companies' %}</a></li>
                    {% else %}
                        <li id="companies-button"><a id="option1" href="{% url 'business:index' %}" class="button-user" role="button">{% trans 'Companies' %}</a></li>
                    {% endif %}
                    <li id="register-button"><a href="{% url 'beta_invite:index' %}" class="button-user" role="button">{% trans 'Sign Up' %}</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock %}

testing_webpage/testing_webpage/templates/transparent_header_base.html
{% extends 'base.html'%}
{% load i18n %}
{% load static %}
{% load app_filters %}
{% load compress %}
{% block header_base_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'testing_webpage/css/transparent_header_base.css' %}">
{% endblock %}
{% block header %}
    <section class="main-section" id="main-section">
        <div class="topnav" id="myTopnav">
            <a href="/staffing" class="logo"><img src="{% static 'business/img/logo-color.png' %}"></a>
            <!--<a class="navButton regular" role="button" onclick="on_login()">INICIA SESIÓN</a>-->
            <a class="navButton" role="button" onclick="on_signup()">CREA TU CUENTA</a>
        </div>
        <h1 class="col-lg-4 main-title">{{ job_title }}</h1>
    </section>
{% endblock %}

testing_webpage/testing_webpage/templates/white_header_base.html
{% extends 'base.html'%}
{% load i18n %}
{% load static %}
{% load app_filters %}
{% load compress %}
{% block header_base_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'testing_webpage/css/white_header_base.css' %}">
{% endblock %}
{% block header %}
    <div class="topnav" id="myTopnav">
        <a href="/staffing" class="logo"><img src="{% static 'business/img/logo-color-negro.png' %}"></a>
        {% if 'seleccion_de_personal' in request.path and 'contactanos' not in request.path %}
            {% if user.is_authenticated %}
                <a href="{% url 'business:logout' %}">{% trans "LOG OUT" %}</a>
                {% if not 'campañas' in request.path %}
                    <a href="{% url 'business:business_campaigns' user|get_business_user_id_from_auth_user %}">{% trans 'My campaigns' %}</a>
                {% endif %}
                <a class="navButton" style="font-size: 15px;width:170px;color: white;border-radius:40px;margin-top: 30px;padding:5px 16px;background:#F47B20;" role="button" href="{% url 'business:start' %}">{% trans '+ NEW JOB POST' %}</a>
            {% else %}
                <a href="{% url 'business:logout' %}">{% trans 'SIGN IN' %}</a>
            {% endif %}
            <!--<a href="#about">Ayuda</a>-->
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
        {% endif %}
    </div>
{% endblock %}


x